---
- name: CentOS | Install the required packages in Redhat derivatives.
  yum:
    name: chrony
    state: "{{ chrony_pkg_state }}"

- name: CentOS | Check if ntpd service exists.
  stat: path="/usr/lib/systemd/system/ntpd.service"
  register: ntpd_service_status

- name: CentOS | Stop and mask ntpd service.
  systemd:
    name: ntpd
    state: stopped
    masked: yes
  when: ntpd_service_status.stat.exists

- name: Copy the chrony.conf template file.
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_location_rhel }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart chrony.

- name: Start and enable chrony service.
  systemd:
    name: "{{ chrony_service_name }}"
    state: "{{ chrony_service_state }}"
    enabled: "{{ chrony_service_enabled }}"

- name: Ensure tzdata package is installed.
  package:
    name: "{{ chrony_tzdata_package }}"
    state: present

- name: Set timezone.
  timezone:
    name: "{{ chrony_timezone }}"
