---
- name: Create download directory.
  file:
    state: directory
    mode: u=rwx,go=rx
    dest: "{{ aws_cli_download_dir }}"

- name: Download.
  get_url:
    url: "{{ aws_cli_url_download }}"
    dest: "{{ aws_cli_download_dir }}/{{ aws_cli_filename }}"
    mode: u=rw,go=r

- name: Unzip package.
  become: yes
  unarchive:
    src: "{{ aws_cli_download_dir }}/{{ aws_cli_filename }}"
    remote_src: yes
    dest: "{{ aws_cli_download_dir }}"
    owner: root
    group: root

- name: Install.
  shell:
    cmd: sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    chdir: "{{ aws_cli_download_dir }}"
